name: ssflow
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.3
  flutter_riverpod: ^1.0.0
  import_sorter: ^4.6.0
  riverpod: ^1.0.0
  simple_logger: ^1.8.1+1
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
